### ISSUE TITLE
auro-radio: unable to tab to a single radio button

### ISSUE THREAD

**Issue by geoffrich** [AlaskaAirlines/auro-radio#10]
## Describe the bug
I am unable to tab to a single radio button that is not placed in a radio group.

## To Reproduce
1. Render the following markup:
```html
<auro-radio id="radio1" label="Yes" name="radioDemo" value="yes"></auro-radio>
```
2. Attempt to tab to it

## Expected behavior
I can tab to the radio button OR we require that single radio buttons are placed within a radio group.

Currently there are multiple examples on the [demo page](https://auro.alaskaair.com/components/auro/radio) that have a single radio button outside of a radio group. If the group is required, we should update our documentation accordingly.

## Desktop (please complete the following information):
 - OS: Windows 10
 - Browser: Chrome

**Comment by blackfalcon** [comment]
Yes. All the tab logic is in the `auro-radio-group` element. So yes, in order to manage a tab state with a single radio button would require a group wrapper. 

I guess I have to ask, is there an actual use case for using a single radio button? That seems counterproductive from a UX perspective. 

If I check it, I have no way to uncheck it. I can get on board that the documentation could be updated to state that any use of a radio button requires a group element.

**Comment by geoffrich** [comment]
I'm not sure if there's a single radio button use case. I agree that the best approach would be updating documentation and examples to always use the radio-group.

**Comment by blackfalcon** [comment]
The docsite was updated to include this information as to remove any opportunity for issue.
