### ISSUE TITLE
auro-radio: incorrect a11y experience 

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-radio#22]
## Describe the bug

Not sure if this [pull request](https://github.com/AlaskaAirlines/WebCoreStyleSheets/pull/66) is the cause, but it's been discovered that when selecting a radio button option on a mobile device, there is a blue halo. 

This is only appearing with a radio-group.

This is not the expected experience when working with an Auro element. 

## To Reproduce
1. Go to https://auro.alaskaair.com/components/auro/radio
1. Click on any option in a radio group
1. See the error

## Expected behavior

When tapping on a radio option, there should be no halo.

## Screenshots

<img width="557" alt="Screen Shot 2021-03-22 at 9 09 05 AM" src="https://user-images.githubusercontent.com/181089/112021225-4b977a00-8aee-11eb-9cd4-67f3f6592fc3.png">

## Smartphone (please complete the following information):
 - OS: iOS
 - Browser: Safari
 - Latest version

**Comment by blackfalcon** [comment]
Issue is currently assigned to @blackfalclon to find root cause of this issue.

**Comment by geoffrich** [comment]
It looks like whatever is compiling the Sass is combining the focus-visible declarations in WCSS, presumably because they share a ruleset:

```css
.js-focus-visible :focus:not(.focus-visible), :focus:not(:focus-visible) { /* whatever */ }
```

[They are separate](https://github.com/AlaskaAirlines/WebCoreStyleSheets/blob/6915f980b6ed1cc73a645bf94f47942cfc56a8ee/src/_core.scss#L59-L74) in the `_core.scss` stylesheet to prevent browsers that do not support :focus-visible from throwing the whole rule out. With how it's currently minified, Safari will not remove focus styles as expected because it does not support focus-visible.

This may be the cause of the issue.
